#!/bin/bash

# if it doesn't exist, create the data director
mkdir -p data

# download and prepare the data
curl -o 'data/lehd_od_2014.csv.gz' http://lehd.ces.census.gov/data/lodes/LODES7/ny/od/ny_od_main_JT05_2014.csv.gz
gunzip data/lehd_od_2014.csv.gz


