#!/bin/bash
## setup_01

## this script prepares the working directory and downloads the raw data we will use in this project

# make sure we are at the top of the git directory
REPOLOC="$(git rev-parse --show-toplevel)"
cd $REPOLOC

# if it doesn't exist, create the data director
mkdir -p data

# download and prepare the data

# 2014 LEHD Origin Destination Table
curl -o 'data/lehd_od_2014.csv.gz' http://lehd.ces.census.gov/data/lodes/LODES7/ny/od/ny_od_main_JT00_2014.csv.gz
gunzip -f data/lehd_od_2014.csv.gz

# NYC Census Blocks 2010
curl -o 'data/NYCCB10.zip' http://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/nycb2010_16c.zip
unzip -o 'data/NYCCB10.zip' -d data/
rm 'data/NYCCB10.zip'

# 2014 Citi Bike Data
# January to August
for m in $(seq 1 8)
do
  curl -o 'data/citibike_20140'$m'.zip' https://s3.amazonaws.com/tripdata/20140$m-citibike-tripdata.zip
  unzip -o data/citibike_20140$m.zip -d data/
  mv 'data/2014-0'$m' - Citi Bike trip data.csv' data/citibike_20140$m.csv
  rm 'data/citibike_20140'$m'.zip'
done

# September to December
for m in $(seq -w 9 12)
do
  curl -o 'data/citibike_2014'$m'.zip' https://s3.amazonaws.com/tripdata/2014$m-citibike-tripdata.zip
  unzip -o data/citibike_2014$m.zip -d data/
  mv 'data/2014'$m'-citibike-tripdata.csv' data/citibike_2014$m.csv
  rm 'data/citibike_2014'$m'.zip'
done

# 2015 Citi Bike Data
for m in $(seq -w 1 12)
do
  curl -o 'data/citibike_2015'$m'.zip' https://s3.amazonaws.com/tripdata/2015$m-citibike-tripdata.zip
  unzip -o data/citibike_2015$m.zip -d data/
  mv 'data/2015'$m'-citibike-tripdata.csv' data/citibike_2015$m.csv
  rm 'data/citibike_2015'$m'.zip'
done

# 2016 Citi Bike Data
for m in $(seq -w 1 11)
do
  curl -o 'data/citibike_2016'$m'.zip' https://s3.amazonaws.com/tripdata/2016$m-citibike-tripdata.zip
  unzip -o data/citibike_2016$m.zip -d data/
  mv 'data/2016'$m'-citibike-tripdata.csv' data/citibike_2016$m.csv
  rm 'data/citibike_2016'$m'.zip'
done

# Demographic data
curl -o data/demo.zip http://www2.census.gov/geo/tiger/TIGER_DP/2011ACS/2011_ACS_5YR_BG_36.gdb.zip

unzip data/demo.zip -d data/
rm data/demo.zip

# subway location data
curl -o data/subway.csv http://data.ny.gov/api/views/i9wp-a4ja/rows.csv?accessType=DOWNLOAD 
