#!/bin/bash

## setup_01

## this script prepares the working directory and downloads the raw data we will use in this project

# if it doesn't exist, create the data director
mkdir -p data

# download and prepare the data

# LEHD Origin Destination Table
curl -o 'data/lehd_od_2014.csv.gz' http://lehd.ces.census.gov/data/lodes/LODES7/ny/od/ny_od_main_JT00_2014.csv.gz
gunzip data/lehd_od_2014.csv.gz

# Citi Bike Data
curl -o 'data/citibike_201401.zip' https://s3.amazonaws.com/tripdata/201401-citibike-tripdata.zip
unzip 'data/citibike_201401.zip' -d data/
mv 'data/2014-01 - Citi Bike trip data.csv' data/citibike_201401.csv
rm 'data/citibike_201401.zip'
